#Casos de prueba
caso1=dict(id_prestamo='RETOS2_001',
    casado='No',
    dependientes=1,
    educacion='Graduado',
    independiente='Si',
    ingreso_deudor=4692,
    ingreso_codeudor=0,
    cantidad_prestamo=106,
    plazo_prestamo=360,
    historia_credito=1,
    tipo_propiedad='Rural')

caso2=dict(id_prestamo='RETOS2_002',
    casado='No',
    dependientes='3+',
    educacion='No Graduado',
    independiente='No',
    ingreso_deudor=1830,
    ingreso_codeudor=0,
    cantidad_prestamo=100,
    plazo_prestamo=360,
    historia_credito=0,
    tipo_propiedad='Urbano')

caso3=dict(id_prestamo='RETOS2_003',
    casado='No',
    dependientes='0',
    educacion='No Graduado',
    independiente='No',
    ingreso_deudor=3748,
    ingreso_codeudor=1668,
    cantidad_prestamo=110,
    plazo_prestamo=360,
    historia_credito=1,
    tipo_propiedad='Semiurbano')